spring:
  flyway:
    baselineOnMigrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    hibernate:
#      ddl-auto: create
#To connect to the database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 0147896325aA
    driver-class-name: org.postgresql.Driver

